### ISSUE TITLE
MetaMap mapped_terms_to_spacy_ann Bug

### ISSUE THREAD

**Issue by zazabar** [NanoNLP/medaCy#74]
#### Description
Conducted in development branch, attempted to metamap a file and generate a spacy annotation file. Got the error listed below.

`Traceback (most recent call last):
  File "medtest.py", line 5, in <module>
    me_ann = medy.mapped_terms_to_spacy_ann(me_dict)
  File "/home/jeff/.local/lib/python3.6/site-packages/medacy/pipeline_components/metamap/metamap.py", line 196, in mapped_terms_to_spacy_ann
    for span in self.get_span_by_term(term): #if a single entity corresonds to a disjunct span
  File "/home/jeff/.local/lib/python3.6/site-packages/medacy/pipeline_components/metamap/metamap.py", line 255, in get_span_by_term
    if int(term['ConceptPIs']['@Count']) == 1:
TypeError: string indices must be integers`

#### Steps/Code to Reproduce
python3 medtest.py

#### Expected Results
Annotation output.

#### Actual Results
See error above

#### Versions
Linux-4.15.0-33-generic-x86_64-with-LinuxMint-19-tara
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
NumPy 1.15.4
SciPy 1.2.0
medacy 0.0.6

**Comment by zazabar** [comment]
Attaching files.
[medtest.zip](https://github.com/NanoNLP/medaCy/files/2722517/medtest.zip)

**Comment by CoreySutphin** [comment]
The error is being thrown because you need to call the ```extract_mapped_terms``` method to actually get the array of terms after mapping the file.  This code snippet should work:
```python
from medacy.pipeline_components import MetaMap

medy = MetaMap(metamap_path="/home/lab/programs/metamap/2016/public_mm")
me_dict = medy.map_file("subtest_in/018636330_DH.txt")
mapped_terms = medy.extract_mapped_terms(me_dict)
me_ann = medy.mapped_terms_to_spacy_ann(mapped_terms)
print(me_ann)
```

Just an FYI, there is also a [Dataset](https://github.com/NanoNLP/medaCy/blob/master/medacy/data/dataset.py) class that handles reading in and metamapping files(can be used to metamap a directory of files at once) that I'd recommend using.  All of MedaCy's features for training models and predicting with them require the data to be packaged in a Dataset object.  [Here's a guide we wrote using it](https://github.com/NanoNLP/medaCy/blob/master/examples/guide/data_management.md#using-a-dataset), feel free to reach out if you have any questions :)
